import Todo, { ITodo, TaskStatus, TaskPriority, TaskCategory } from '@/models/Todo';
import { NLPService, ParsedTaskInfo } from './nlpService';
import ParallelProcessor, { BatchProcessingResult } from './parallelProcessor';
import connectDB from '@/lib/mongodb';

export interface CreateTodoInput {
  rawInput: string;
  userId: string;
  projectId?: string;
}

export interface UpdateTodoInput {
  title?: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  category?: TaskCategory;
  dueDate?: Date;
  tags?: string[];
  progressPercentage?: number;
  notes?: string;
}

export interface SearchFilters {
  status?: TaskStatus;
  priority?: TaskPriority;
  category?: TaskCategory;
  projectId?: string;
  minPriorityScore?: number;
  isOverdue?: boolean;
  dueDateRange?: {
    start?: Date;
    end?: Date;
  };
}

export interface RecommendationItem {
  type: 'overdue_tasks' | 'high_priority' | 'due_soon' | 'quick_wins' | 'stalled_tasks';
  priority: 'high' | 'medium' | 'low';
  message: string;
  todos: ITodo[];
  actionSuggestion?: string;
}

export class AITodoService {
  private nlpService: NLPService;
  private parallelProcessor: ParallelProcessor<string, ITodo>;

  constructor() {
    this.nlpService = new NLPService();
    this.parallelProcessor = new ParallelProcessor<string, ITodo>({
      maxWorkers: 4,
      batchSize: 20,
      maxConcurrentBatches: 3,
      timeoutMs: 30000,
    });
  }

  /**
   * Create an AI-enhanced todo from natural language input
   */
  async createAIEnhancedTodo(input: CreateTodoInput): Promise<ITodo> {
    await connectDB();

    try {
      // Parse natural language input
      const parsedInfo = await this.nlpService.parseNaturalLanguageTask(input.rawInput);
      
      // Generate AI metadata
      const aiMetadata = await this.nlpService.generateAIMetadata(input.rawInput, parsedInfo);
      
      // Calculate AI priority score
      const aiPriorityScore = this.calculateAIPriorityScore(parsedInfo);
      
      // Create todo document
      const todoData = {
        title: parsedInfo.title,
        description: parsedInfo.description,
        priority: parsedInfo.priority,
        category: parsedInfo.category,
        dueDate: parsedInfo.dueDate,
        userId: input.userId,
        projectId: input.projectId,
        tags: parsedInfo.tags,
        aiMetadata,
        autoGenerated: true,
        aiPriorityScore,
        estimatedDuration: parsedInfo.estimatedDuration,
        complexityScore: parsedInfo.complexityScore,
        rawInput: input.rawInput,
        progressPercentage: 0,
        relationships: [],
      };

      const todo = new Todo(todoData);
      await todo.save();

      console.log(`Created AI-enhanced todo ${todo._id} for user ${input.userId}`);
      return todo;
    } catch (error) {
      console.error('Error creating AI-enhanced todo:', error);
      throw new Error(`Failed to create AI-enhanced todo: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Batch create todos using parallel processing
   */
  async batchCreateTodos(
    todoInputs: string[],
    userId: string,
    projectId?: string
  ): Promise<BatchProcessingResult<ITodo>> {
    const processSingleTodo = async (rawInput: string): Promise<ITodo> => {
      return await this.createAIEnhancedTodo({
        rawInput,
        userId,
        projectId,
      });
    };

    return await this.parallelProcessor.processWithRetry(
      todoInputs,
      processSingleTodo,
      {
        maxRetries: 2,
        retryDelay: 1000,
        getItemId: (input) => input.substring(0, 50), // Use first 50 chars as ID
      }
    );
  }

  /**
   * Update a todo with AI enhancements
   */
  async updateTodo(todoId: string, updateData: UpdateTodoInput): Promise<ITodo> {
    await connectDB();

    try {
      const todo = await Todo.findById(todoId);
      if (!todo) {
        throw new Error(`Todo ${todoId} not found`);
      }

      // Update fields
      Object.keys(updateData).forEach(key => {
        if (updateData[key as keyof UpdateTodoInput] !== undefined) {
          (todo as any)[key] = updateData[key as keyof UpdateTodoInput];
        }
      });

      // Handle status changes
      if (updateData.status === TaskStatus.COMPLETED && !todo.completedAt) {
        todo.completedAt = new Date();
        todo.progressPercentage = 100;
      } else if (updateData.status !== TaskStatus.COMPLETED && todo.completedAt) {
        todo.completedAt = undefined;
      }

      await todo.save();
      return todo;
    } catch (error) {
      console.error(`Error updating todo ${todoId}:`, error);
      throw new Error(`Failed to update todo: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Intelligent search with AI-powered filtering
   */
  async intelligentSearch(
    query: string,
    userId: string,
    filters: SearchFilters = {},
    limit: number = 50
  ): Promise<ITodo[]> {
    await connectDB();

    try {
      // Parse search query using NLP
      const parsedQuery = await this.nlpService.parseNaturalLanguageTask(query);
      
      // Build MongoDB query
      const mongoQuery: any = { userId };

      // Apply AI-enhanced filters
      if (parsedQuery.category) {
        mongoQuery.category = parsedQuery.category;
      }

      if (parsedQuery.priority) {
        mongoQuery.priority = parsedQuery.priority;
      }

      if (parsedQuery.dueDate) {
        // Search for todos due around the parsed date (±1 day)
        const dayBefore = new Date(parsedQuery.dueDate);
        dayBefore.setDate(dayBefore.getDate() - 1);
        const dayAfter = new Date(parsedQuery.dueDate);
        dayAfter.setDate(dayAfter.getDate() + 1);
        
        mongoQuery.dueDate = {
          $gte: dayBefore,
          $lte: dayAfter,
        };
      }

      // Text search in title, description, and tags
      if (parsedQuery.tags.length > 0) {
        const searchTerms = [parsedQuery.title, ...parsedQuery.tags].filter(Boolean);
        if (searchTerms.length > 0) {
          mongoQuery.$or = searchTerms.flatMap(term => [
            { title: { $regex: term, $options: 'i' } },
            { description: { $regex: term, $options: 'i' } },
            { tags: { $in: [new RegExp(term, 'i')] } },
          ]);
        }
      }

      // Apply additional filters
      if (filters.status) mongoQuery.status = filters.status;
      if (filters.priority) mongoQuery.priority = filters.priority;
      if (filters.category) mongoQuery.category = filters.category;
      if (filters.projectId) mongoQuery.projectId = filters.projectId;
      if (filters.minPriorityScore) mongoQuery.aiPriorityScore = { $gte: filters.minPriorityScore };
      
      if (filters.isOverdue) {
        mongoQuery.dueDate = { $lt: new Date() };
        mongoQuery.status = { $ne: TaskStatus.COMPLETED };
      }

      if (filters.dueDateRange) {
        const dateFilter: any = {};
        if (filters.dueDateRange.start) dateFilter.$gte = filters.dueDateRange.start;
        if (filters.dueDateRange.end) dateFilter.$lte = filters.dueDateRange.end;
        if (Object.keys(dateFilter).length > 0) {
          mongoQuery.dueDate = dateFilter;
        }
      }

      // Execute query with sorting
      const todos = await Todo.find(mongoQuery)
        .sort({ aiPriorityScore: -1, createdAt: -1 })
        .limit(limit)
        .exec();

      return todos;
    } catch (error) {
      console.error('Error in intelligent search:', error);
      throw new Error(`Search failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Generate AI-powered recommendations
   */
  async getAIRecommendations(userId: string, limit: number = 10): Promise<RecommendationItem[]> {
    await connectDB();

    try {
      const recommendations: RecommendationItem[] = [];
      const now = new Date();

      // Get user's active todos
      const activeTodos = await Todo.find({
        userId,
        status: { $ne: TaskStatus.COMPLETED },
      }).exec();

      // 1. Overdue tasks
      const overdueTodos = activeTodos.filter(todo => 
        todo.dueDate && todo.dueDate < now
      );

      if (overdueTodos.length > 0) {
        recommendations.push({
          type: 'overdue_tasks',
          priority: 'high',
          message: `You have ${overdueTodos.length} overdue task${overdueTodos.length > 1 ? 's' : ''}`,
          todos: overdueTodos.slice(0, 5),
          actionSuggestion: 'Consider rescheduling or completing these tasks immediately',
        });
      }

      // 2. High priority tasks
      const highPriorityTodos = activeTodos.filter(todo =>
        [TaskPriority.HIGH, TaskPriority.URGENT].includes(todo.priority) &&
        todo.status === TaskStatus.PENDING
      );

      if (highPriorityTodos.length > 0) {
        recommendations.push({
          type: 'high_priority',
          priority: 'medium',
          message: `Focus on ${highPriorityTodos.length} high-priority task${highPriorityTodos.length > 1 ? 's' : ''}`,
          todos: highPriorityTodos.slice(0, 3),
          actionSuggestion: 'Prioritize these tasks in your schedule',
        });
      }

      // 3. Due soon tasks
      const tomorrow = new Date(now);
      tomorrow.setDate(tomorrow.getDate() + 1);
      
      const dueSoonTodos = activeTodos.filter(todo =>
        todo.dueDate && 
        todo.dueDate > now && 
        todo.dueDate <= tomorrow
      );

      if (dueSoonTodos.length > 0) {
        recommendations.push({
          type: 'due_soon',
          priority: 'medium',
          message: `${dueSoonTodos.length} task${dueSoonTodos.length > 1 ? 's' : ''} due soon`,
          todos: dueSoonTodos,
          actionSuggestion: 'Plan time for these upcoming deadlines',
        });
      }

      // 4. Quick wins (low complexity, high impact)
      const quickWinTodos = activeTodos
        .filter(todo => 
          todo.complexityScore < 0.4 && 
          todo.aiPriorityScore > 0.6 &&
          todo.status === TaskStatus.PENDING
        )
        .slice(0, 3);

      if (quickWinTodos.length > 0) {
        recommendations.push({
          type: 'quick_wins',
          priority: 'low',
          message: 'Quick wins to boost productivity',
          todos: quickWinTodos,
          actionSuggestion: 'Complete these for quick progress',
        });
      }

      // 5. Stalled tasks (in progress for too long)
      const weekAgo = new Date(now);
      weekAgo.setDate(weekAgo.getDate() - 7);
      
      const stalledTodos = activeTodos.filter(todo =>
        todo.status === TaskStatus.IN_PROGRESS &&
        todo.updatedAt < weekAgo
      );

      if (stalledTodos.length > 0) {
        recommendations.push({
          type: 'stalled_tasks',
          priority: 'medium',
          message: `${stalledTodos.length} task${stalledTodos.length > 1 ? 's' : ''} may be stalled`,
          todos: stalledTodos.slice(0, 3),
          actionSuggestion: 'Review progress and identify blockers',
        });
      }

      return recommendations.slice(0, limit);
    } catch (error) {
      console.error('Error generating AI recommendations:', error);
      return [];
    }
  }

  /**
   * Get todo by ID
   */
  async getTodoById(todoId: string): Promise<ITodo | null> {
    await connectDB();
    
    try {
      return await Todo.findById(todoId).exec();
    } catch (error) {
      console.error(`Error getting todo ${todoId}:`, error);
      return null;
    }
  }

  /**
   * Get todos for a user with pagination
   */
  async getUserTodos(
    userId: string,
    filters: SearchFilters = {},
    page: number = 1,
    limit: number = 50
  ): Promise<{ todos: ITodo[]; total: number; page: number; totalPages: number }> {
    await connectDB();

    try {
      const query: any = { userId };
      
      // Apply filters
      if (filters.status) query.status = filters.status;
      if (filters.priority) query.priority = filters.priority;
      if (filters.category) query.category = filters.category;
      if (filters.projectId) query.projectId = filters.projectId;

      const skip = (page - 1) * limit;
      
      const [todos, total] = await Promise.all([
        Todo.find(query)
          .sort({ aiPriorityScore: -1, createdAt: -1 })
          .skip(skip)
          .limit(limit)
          .exec(),
        Todo.countDocuments(query).exec(),
      ]);

      return {
        todos,
        total,
        page,
        totalPages: Math.ceil(total / limit),
      };
    } catch (error) {
      console.error('Error getting user todos:', error);
      throw new Error(`Failed to get todos: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Delete a todo
   */
  async deleteTodo(todoId: string): Promise<boolean> {
    await connectDB();

    try {
      const result = await Todo.findByIdAndDelete(todoId).exec();
      return !!result;
    } catch (error) {
      console.error(`Error deleting todo ${todoId}:`, error);
      return false;
    }
  }

  /**
   * Get processing statistics
   */
  getProcessingStats() {
    return this.parallelProcessor.getStats();
  }

  /**
   * Calculate AI priority score based on parsed information
   */
  private calculateAIPriorityScore(parsedInfo: ParsedTaskInfo): number {
    let score = 0.5; // Base score

    // Priority boost
    const priorityScores = {
      [TaskPriority.LOW]: 0.2,
      [TaskPriority.MEDIUM]: 0.5,
      [TaskPriority.HIGH]: 0.8,
      [TaskPriority.URGENT]: 1.0,
    };
    score += priorityScores[parsedInfo.priority] * 0.4;

    // Due date urgency
    if (parsedInfo.dueDate) {
      const now = new Date();
      const daysUntilDue = Math.ceil((parsedInfo.dueDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
      
      if (daysUntilDue <= 0) {
        score += 0.3; // Overdue
      } else if (daysUntilDue <= 1) {
        score += 0.2; // Due today/tomorrow
      } else if (daysUntilDue <= 7) {
        score += 0.1; // Due this week
      }
    }

    // Confidence boost
    score += parsedInfo.confidenceScore * 0.1;

    return Math.min(score, 1.0);
  }
}

export default AITodoService;
