import mongoose, { Document, Schema, Model } from 'mongoose';

// Enums
export enum TaskStatus {
  PENDING = 'pending',
  IN_PROGRESS = 'in_progress',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled',
  ON_HOLD = 'on_hold',
}

export enum TaskPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent',
}

export enum TaskCategory {
  WORK = 'work',
  PERSONAL = 'personal',
  HEALTH = 'health',
  FINANCE = 'finance',
  EDUCATION = 'education',
  SHOPPING = 'shopping',
  TRAVEL = 'travel',
  OTHER = 'other',
}

// AI Metadata Interface
export interface AIMetadata {
  confidenceScore: number;
  extractedEntities: Record<string, any>;
  sentimentScore: number;
  keywords: string[];
  suggestedTags: string[];
  processingTimestamp: Date;
  nlpVersion?: string;
  modelUsed?: string;
}

// Task Relationship Interface
export interface TaskRelationship {
  relatedTaskId: mongoose.Types.ObjectId;
  relationshipType: 'dependency' | 'subtask' | 'related';
  description?: string;
}

// Todo Interface
export interface ITodo extends Document {
  _id: mongoose.Types.ObjectId;
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  category?: TaskCategory;
  
  // Temporal fields
  createdAt: Date;
  updatedAt: Date;
  dueDate?: Date;
  completedAt?: Date;
  
  // AI-enhanced fields
  aiMetadata?: AIMetadata;
  autoGenerated: boolean;
  aiPriorityScore: number;
  estimatedDuration?: number; // in minutes
  complexityScore: number;
  
  // User and project association
  userId: string;
  projectId?: string;
  tags: string[];
  
  // Task relationships
  relationships: TaskRelationship[];
  
  // Raw input for AI processing
  rawInput?: string;
  
  // Progress tracking
  progressPercentage: number;
  timeSpent?: number; // in minutes
  
  // Collaboration
  assignedTo?: string[];
  watchers?: string[];
  
  // Attachments and notes
  attachments?: string[];
  notes?: string;
}

// Todo Schema
const TodoSchema = new Schema<ITodo>({
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 255,
    index: true,
  },
  description: {
    type: String,
    trim: true,
    maxlength: 2000,
  },
  status: {
    type: String,
    enum: Object.values(TaskStatus),
    default: TaskStatus.PENDING,
    index: true,
  },
  priority: {
    type: String,
    enum: Object.values(TaskPriority),
    default: TaskPriority.MEDIUM,
    index: true,
  },
  category: {
    type: String,
    enum: Object.values(TaskCategory),
    index: true,
  },
  
  // Temporal fields
  createdAt: {
    type: Date,
    default: Date.now,
    index: true,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
  dueDate: {
    type: Date,
    index: true,
  },
  completedAt: {
    type: Date,
  },
  
  // AI-enhanced fields
  aiMetadata: {
    confidenceScore: {
      type: Number,
      min: 0,
      max: 1,
      default: 0,
    },
    extractedEntities: {
      type: Schema.Types.Mixed,
      default: {},
    },
    sentimentScore: {
      type: Number,
      min: -1,
      max: 1,
      default: 0,
    },
    keywords: [{
      type: String,
    }],
    suggestedTags: [{
      type: String,
    }],
    processingTimestamp: {
      type: Date,
      default: Date.now,
    },
    nlpVersion: String,
    modelUsed: String,
  },
  autoGenerated: {
    type: Boolean,
    default: false,
  },
  aiPriorityScore: {
    type: Number,
    min: 0,
    max: 1,
    default: 0.5,
    index: true,
  },
  estimatedDuration: {
    type: Number,
    min: 0,
  },
  complexityScore: {
    type: Number,
    min: 0,
    max: 1,
    default: 0.3,
  },
  
  // User and project association
  userId: {
    type: String,
    required: true,
    index: true,
  },
  projectId: {
    type: String,
    index: true,
  },
  tags: [{
    type: String,
    trim: true,
  }],
  
  // Task relationships
  relationships: [{
    relatedTaskId: {
      type: Schema.Types.ObjectId,
      ref: 'Todo',
    },
    relationshipType: {
      type: String,
      enum: ['dependency', 'subtask', 'related'],
      required: true,
    },
    description: String,
  }],
  
  // Raw input for AI processing
  rawInput: {
    type: String,
    maxlength: 1000,
  },
  
  // Progress tracking
  progressPercentage: {
    type: Number,
    min: 0,
    max: 100,
    default: 0,
  },
  timeSpent: {
    type: Number,
    min: 0,
    default: 0,
  },
  
  // Collaboration
  assignedTo: [{
    type: String,
  }],
  watchers: [{
    type: String,
  }],
  
  // Attachments and notes
  attachments: [{
    type: String,
  }],
  notes: {
    type: String,
    maxlength: 5000,
  },
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true },
});

// Indexes for performance
TodoSchema.index({ userId: 1, status: 1 });
TodoSchema.index({ userId: 1, priority: 1 });
TodoSchema.index({ userId: 1, dueDate: 1 });
TodoSchema.index({ userId: 1, aiPriorityScore: -1 });
TodoSchema.index({ userId: 1, createdAt: -1 });
TodoSchema.index({ title: 'text', description: 'text', tags: 'text' });

// Virtual for overdue status
TodoSchema.virtual('isOverdue').get(function() {
  return this.dueDate && this.dueDate < new Date() && this.status !== TaskStatus.COMPLETED;
});

// Virtual for days until due
TodoSchema.virtual('daysUntilDue').get(function() {
  if (!this.dueDate) return null;
  const now = new Date();
  const diffTime = this.dueDate.getTime() - now.getTime();
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
});

// Pre-save middleware
TodoSchema.pre('save', function(next) {
  this.updatedAt = new Date();
  
  // Set completed date when status changes to completed
  if (this.status === TaskStatus.COMPLETED && !this.completedAt) {
    this.completedAt = new Date();
    this.progressPercentage = 100;
  }
  
  // Reset completed date if status changes from completed
  if (this.status !== TaskStatus.COMPLETED && this.completedAt) {
    this.completedAt = undefined;
  }
  
  next();
});

// Static methods
TodoSchema.statics.findByUser = function(userId: string) {
  return this.find({ userId });
};

TodoSchema.statics.findOverdue = function(userId: string) {
  return this.find({
    userId,
    dueDate: { $lt: new Date() },
    status: { $ne: TaskStatus.COMPLETED }
  });
};

TodoSchema.statics.findByPriority = function(userId: string, priority: TaskPriority) {
  return this.find({ userId, priority });
};

// Instance methods
TodoSchema.methods.markCompleted = function() {
  this.status = TaskStatus.COMPLETED;
  this.completedAt = new Date();
  this.progressPercentage = 100;
  return this.save();
};

TodoSchema.methods.addRelationship = function(relatedTaskId: mongoose.Types.ObjectId, type: string, description?: string) {
  this.relationships.push({
    relatedTaskId,
    relationshipType: type as 'dependency' | 'subtask' | 'related',
    description
  });
  return this.save();
};

// Create and export the model
const Todo: Model<ITodo> = mongoose.models.Todo || mongoose.model<ITodo>('Todo', TodoSchema);

export default Todo;
